application_port: 8080
database:
  host: "127.0.0.1"
  port: 8091
  username: "Administrator"
  password: "password"
  bucket_name: "transactions"
  scope_name: "transactions"
  collection_name: "transactions"
  test_bucket_name: "test_data"
  test_scope_name: "test_data"
  test_collection_name: "test_data"